# Business Understanding



### 🏡 **Backstory**

A mid-sized real estate company, **UrbanNest Realty**, has been helping clients buy and sell homes in major metropolitan areas. With the market becoming increasingly competitive and dynamic, the company wants to leverage data science to offer more accurate pricing insights to buyers, sellers, and agents.

Historically, property pricing was based on intuition, basic comparable sales, and experience. However, this approach often resulted in underpricing or overpricing, leading to missed opportunities or prolonged listings. The company now aims to develop a machine learning model to predict the selling price of houses based on various features such as location, size, number of rooms, amenities, and more.

---

### 💼 **Business Problem**

The company currently lacks a robust, data-driven method for accurately pricing homes. This leads to:
- Properties being listed at non-competitive prices
- Reduced buyer interest or unnecessary negotiation
- Loss of client trust due to inconsistent valuation
- Delays in the buying/selling cycle

These issues affect the company's revenue and customer satisfaction.

---

### 🎯 **Business Objective**

To develop a predictive model that accurately estimates house prices based on historical data. The goal is to:
- Provide agents and clients with a reliable price range for properties
- Reduce overpricing/underpricing of homes
- Shorten listing-to-sale time
- Increase transaction success rate and client satisfaction

This model will serve as a core tool in their digital platform for agents and customers.

---

### ⚠️ **Constraints**

1. **Data Availability:** Some property features (e.g., interior quality, recent renovations) may not be consistently available.
2. **Dynamic Market Conditions:** Real estate prices fluctuate due to seasonality, economic factors, and local trends.
3. **Regulatory Differences:** Regional laws or zoning rules can affect pricing but may not be captured in the data.
4. **Model Interpretability:** The business prefers a model that’s not only accurate but also easy to explain to non-technical stakeholders.
5. **Deployment Limitations:** The final solution must run efficiently on the company’s existing cloud infrastructure.

House Price Prediction is a Regression Model       
=> Supervised ML(Input & Targt feature is present) -> Labelled Data -> Target Feature is (Continuous) -> Regression Model
- Linear Regression
- KNN Regressor
- Decision Tree Regressor
- Random Forest Regressor
- Support Vector Regressor

## **1. Data Understanding**

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r"C:\Users\GA\Desktop\ML\housing_price_dataset.csv")
df

       SquareFeet  Bedrooms  Bathrooms Neighborhood  YearBuilt          Price
0            2126         4          1        Rural       1969  215355.283618
1            2459         3          2        Rural       1980  195014.221626
2            1860         2          1       Suburb       1970  306891.012076
3            2294         2          1        Urban       1996  206786.787153
4            2130         5          2       Suburb       2001  272436.239065
...           ...       ...        ...          ...        ...            ...
49995        1282         5          3        Rural       1975  100080.865895
49996        2854         2          2       Suburb       1988  374507.656727
49997        2979         5          3       Suburb       1962  384110.555590
49998        2596         5          2        Rural       1984  380512.685957
49999        1572         5          3        Rural       2011  221618.583218

[50000 rows x 6 columns]

In [3]:
df.shape

(50000, 6)

In [4]:
df.dtypes

SquareFeet        int64
Bedrooms          int64
Bathrooms         int64
Neighborhood     object
YearBuilt         int64
Price           float64
dtype: object

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   SquareFeet    50000 non-null  int64
 1   Bedrooms      50000 non-null  int64
 2   Bathrooms     50000 non-null  int64
 3   Neighborhood  50000 non-null  object
 4   YearBuilt     50000 non-null  int64
 5   Price         50000 non-null  float64
dtypes: float64(1), int64(4), object(1)
memory usage: 2.3+ MB

## **2. Data Pre-processing**

### **(A) EDA -**

In [6]:
df.describe(include = 'all')

,SquareFeet,Bedrooms,Bathrooms,Neighborhood,YearBuilt,Price
count,50000.000000,50000.000000,50000.000000,50000,50000.000000,50000.000000
unique,NaN,NaN,NaN,3,NaN,NaN
top,NaN,NaN,NaN,Suburb,NaN,NaN
freq,NaN,NaN,NaN,16721,NaN,NaN
mean,2006.374680,3.498700,1.995420,NaN,1985.404420,224827.325151
std,575.513241,1.116326,0.815851,NaN,20.719377,76141.842966
min,1000.000000,2.000000,1.000000,NaN,1950.000000,-36588.165397
25%,1513.000000,3.000000,1.000000,NaN,1967.000000,169955.860225
50%,2007.000000,3.000000,2.000000,NaN,1985.000000,225052.141166
75%,2506.000000,4.000000,3.000000,NaN,2003.000000,279373.630052
max,2999.000000,5.000000,3.000000,NaN,2021.000000,492195.259972

In [7]:
[ df['SquareFeet'].min() , df['SquareFeet'].max()]

[1000, 2999]

#### **Visualize the Data -**

### **(B) Data Cleaning -**

In [8]:
df.duplicated().sum() # No Duplicates

np.int64(0)

In [9]:
df.isna().sum() # No Missing Values

SquareFeet      0
Bedrooms        0
Bathrooms       0
Neighborhood    0
YearBuilt       0
Price           0
dtype: int64

In [10]:
df['Price'].min()

-36588.16539749279

In [11]:
df[df['Price'] < 0]

       SquareFeet  Bedrooms  Bathrooms Neighborhood  YearBuilt         Price
1266         1024         2          2        Urban       2006 -24715.242482
2310         1036         4          1       Suburb       1983  -7550.504574
3630         1235         3          2        Rural       2012 -19871.251146
4162         1352         5          2       Suburb       1977 -10608.359522
5118         1140         4          1        Urban       2020 -23911.003119
5951         1097         4          3        Rural       1981  -4537.418615
6355         1016         5          2        Rural       1997 -13803.684059
8720         1235         3          1        Urban       1952 -24183.000515
9611         1131         3          3        Urban       1959 -13692.026068
10597        1177         2          3        Urban       2010   -434.097124
11991        1213         4          1       Suburb       2020  -4910.415323
17442        1600         2          3        Rural       1989  -8238.884499
17706        1080         5          1        Rural       1955 -28774.998022
20211        1049         3          1        Rural       2005 -18159.685676
20759        1036         2          2        Urban       1957  -4810.724320
23650        1024         4          3       Suburb       1953  -4295.932176
25459        1106         2          2        Urban       1984  -7177.628532
29827        1173         5          2        Rural       1988   -847.895073
30171        1066         3          1        Rural       1964   -602.209099
33666        1013         5          2        Urban       1960 -36588.165397
35553        1374         4          3        Urban       1996  -4771.570194
36929        1078         5          1       Suburb       2015  -6159.039213

In [12]:
df[df['Price'] < 0] * -1

       SquareFeet  Bedrooms  Bathrooms Neighborhood  YearBuilt         Price
1266        -1024        -2         -2                   -2006  24715.242482
2310        -1036        -4         -1                   -1983   7550.504574
3630        -1235        -3         -2                   -2012  19871.251146
4162        -1352        -5         -2                   -1977  10608.359522
5118        -1140        -4         -1                   -2020  23911.003119
5951        -1097        -4         -3                   -1981   4537.418615
6355        -1016        -5         -2                   -1997  13803.684059
8720        -1235        -3         -1                   -1952  24183.000515
9611        -1131        -3         -3                   -1959  13692.026068
10597       -1177        -2         -3                   -2010    434.097124
11991       -1213        -4         -1                   -2020   4910.415323
17442       -1600        -2         -3                   -1989   8238.884499
17706       -1080        -5         -1                   -1955  28774.998022
20211       -1049        -3         -1                   -2005  18159.685676
20759       -1036        -2         -2                   -1957   4810.724320
23650       -1024        -4         -3                   -1953   4295.932176
25459       -1106        -2         -2                   -1984   7177.628532
29827       -1173        -5         -2                   -1988    847.895073
30171       -1066        -3         -1                   -1964    602.209099
33666       -1013        -5         -2                   -1960  36588.165397
35553       -1374        -4         -3                   -1996   4771.570194
36929       -1078        -5         -1                   -2015   6159.039213

In [13]:
import numpy as np

In [14]:
np.abs(df['Price']).min()

154.77912007166017

In [15]:
df['Price'] = np.abs(df['Price']) 
df['Price']

0        215355.283618
1        195014.221626
2        306891.012076
3        206786.787153
4        272436.239065
             ...
49995    100080.865895
49996    374507.656727
49997    384110.555590
49998    380512.685957
49999    221618.583218
Name: Price, Length: 50000, dtype: float64

In [16]:
df.describe(include = 'all')

,SquareFeet,Bedrooms,Bathrooms,Neighborhood,YearBuilt,Price
count,50000.000000,50000.000000,50000.000000,50000,50000.000000,50000.000000
unique,NaN,NaN,NaN,3,NaN,NaN
top,NaN,NaN,NaN,Suburb,NaN,NaN
freq,NaN,NaN,NaN,16721,NaN,NaN
mean,2006.374680,3.498700,1.995420,NaN,1985.404420,224838.070900
std,575.513241,1.116326,0.815851,NaN,20.719377,76110.105518
min,1000.000000,2.000000,1.000000,NaN,1950.000000,154.779120
25%,1513.000000,3.000000,1.000000,NaN,1967.000000,169955.860225
50%,2007.000000,3.000000,2.000000,NaN,1985.000000,225052.141166
75%,2506.000000,4.000000,3.000000,NaN,2003.000000,279373.630052
max,2999.000000,5.000000,3.000000,NaN,2021.000000,492195.259972

In [17]:
df['Price'].min()

154.77912007166017

In [18]:
df.head()

   SquareFeet  Bedrooms  Bathrooms Neighborhood  YearBuilt          Price
0        2126         4          1        Rural       1969  215355.283618
1        2459         3          2        Rural       1980  195014.221626
2        1860         2          1       Suburb       1970  306891.012076
3        2294         2          1        Urban       1996  206786.787153
4        2130         5          2       Suburb       2001  272436.239065

### **Golden Rule - Machine only understands the Numbers**

In [19]:
df['Neighborhood'].unique()

array(['Rural', 'Suburb', 'Urban'], dtype=object)

In [20]:
df['Neighborhood'] = df['Neighborhood'].map({'Rural': 0 , 'Suburb': 1 , 'Urban': 2}) # View version

In [21]:
df

       SquareFeet  Bedrooms  Bathrooms  Neighborhood  YearBuilt          Price
0            2126         4          1             0       1969  215355.283618
1            2459         3          2             0       1980  195014.221626
2            1860         2          1             1       1970  306891.012076
3            2294         2          1             2       1996  206786.787153
4            2130         5          2             1       2001  272436.239065
...           ...       ...        ...           ...        ...            ...
49995        1282         5          3             0       1975  100080.865895
49996        2854         2          2             1       1988  374507.656727
49997        2979         5          3             1       1962  384110.555590
49998        2596         5          2             0       1984  380512.685957
49999        1572         5          3             0       2011  221618.583218

[50000 rows x 6 columns]

## **3. Model Building**
### Pre-processed Data + Algorithm -> Model
- (x)Input Features - [SquareFeet , Bedrooms , Bathrooms , Neighborhood , YearBuilt]
- (y)Output(Target) Feature - 	[Price]

In [22]:
df

       SquareFeet  Bedrooms  Bathrooms  Neighborhood  YearBuilt          Price
0            2126         4          1             0       1969  215355.283618
1            2459         3          2             0       1980  195014.221626
2            1860         2          1             1       1970  306891.012076
3            2294         2          1             2       1996  206786.787153
4            2130         5          2             1       2001  272436.239065
...           ...       ...        ...           ...        ...            ...
49995        1282         5          3             0       1975  100080.865895
49996        2854         2          2             1       1988  374507.656727
49997        2979         5          3             1       1962  384110.555590
49998        2596         5          2             0       1984  380512.685957
49999        1572         5          3             0       2011  221618.583218

[50000 rows x 6 columns]

### **Sepaerate the Input Feature(x) & Target/Output Feature(y)**

In [23]:
x = df.drop(columns = ['Price'])
x.head()

   SquareFeet  Bedrooms  Bathrooms  Neighborhood  YearBuilt
0        2126         4          1             0       1969
1        2459         3          2             0       1980
2        1860         2          1             1       1970
3        2294         2          1             2       1996
4        2130         5          2             1       2001

In [24]:
y = df['Price']
y.head()

0    215355.283618
1    195014.221626
2    306891.012076
3    206786.787153
4    272436.239065
Name: Price, dtype: float64

In [25]:
pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\ga\anaconda3\envs\eda-tools\lib\site-packages (1.7.2)
Requirement already satisfied: numpy>=1.22.0 in c:\users\ga\anaconda3\envs\eda-tools\lib\site-packages (from scikit-learn) (2.2.6)
Requirement already satisfied: scipy>=1.8.0 in c:\users\ga\anaconda3\envs\eda-tools\lib\site-packages (from scikit-learn) (1.15.3)
Requirement already satisfied: joblib>=1.2.0 in c:\users\ga\anaconda3\envs\eda-tools\lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\ga\anaconda3\envs\eda-tools\lib\site-packages (from scikit-learn) (3.6.0)
Note: you may need to restart the kernel to use updated packages.

In [26]:
from sklearn.model_selection import train_test_split

In [27]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 42) # Can also give 23
x_train,x_test,y_train,y_test

(       SquareFeet  Bedrooms  Bathrooms  Neighborhood  YearBuilt
 39087        2498         2          3             0       2021
 30893        2380         5          3             2       1977
 45278        2274         5          2             2       1957
 16398        2215         5          1             1       1977
 13653        2078         2          3             1       1962
 ...           ...       ...        ...           ...        ...
 11284        2166         5          3             1       1996
 44732        2463         4          1             2       1953
 38158        2812         4          2             2       2010
 860          2188         3          1             2       1979
 15795        2649         5          3             0       1953

 [40000 rows x 5 columns],
        SquareFeet  Bedrooms  Bathrooms  Neighborhood  YearBuilt
 33553        1894         5          1             0       1975
 9427         1001         5          3             1       1963
 199          2264         4          3             1       1964
 12447        2299         5          1             1       1999
 39489        2651         2          1             1       1951
 ...           ...       ...        ...           ...        ...
 28567        2005         3          3             2       1966
 25079        1725         4          2             1       1960
 18707        2885         3          2             2       1980
 15200        1674         5          2             2       1967
 5857         2229         3          2             0       1989

 [10000 rows x 5 columns],
 39087    288178.195769
 30893    374155.921378
 45278    242571.549240
 16398    150048.317779
 13653    241134.908315
              ...
 11284    324396.846219
 44732    319266.944411
 38158    248092.662727
 860      132414.177622
 15795    288751.049986
 Name: Price, Length: 40000, dtype: float64,
 33553    170835.035713
 9427     126913.469998
 199      246611.883092
 12447    244250.462969
 39489    271127.650112
              ...
 28567    199265.817701
 25079    241869.621812
 18707    352184.123976
 15200    244830.805238
 5857     246512.284597
 Name: Price, Length: 10000, dtype: float64)

In [28]:
x_train.shape

(40000, 5)

In [29]:
y_train.shape

(40000,)

### **Linear Regression**

In [30]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [31]:
lr_model = LinearRegression()

In [32]:
lr_model.fit(x_train,y_train)

LinearRegression()

In [33]:
y_pred = lr_model.predict(x_test)
y_pred

array([217919.34482538, 135936.26542501, 256134.12536881, ...,
       310231.94111464, 200503.97277521, 243601.00606826], shape=(10000,))

In [34]:
mean_squared_error(y_test,y_pred)

2435389464.539427

### **KNN Algorithm**

In [35]:
from sklearn.neighbors import KNeighborsRegressor

In [36]:
knn_model = KNeighborsRegressor()
knn_model.fit(x_train,y_train)
y_pred = knn_model.predict(x_test)
mean_squared_error(y_test,y_pred)

2975575455.8445354

### **Decision Tree**

In [37]:
from sklearn.tree import DecisionTreeRegressor

In [38]:
dt_model = DecisionTreeRegressor()
dt_model.fit(x_train,y_train)
y_pred = dt_model.predict(x_test)
mean_squared_error(y_test,y_pred)

5171388744.192384

### **Random Forest**

In [39]:
from sklearn.ensemble import RandomForestRegressor

In [40]:
rf_model = RandomForestRegressor()
rf_model.fit(x_train,y_train)
y_pred = rf_model.predict(x_test)
mean_squared_error(y_test,y_pred)

2770279579.913478

### **Support Vector**
- Its very slow while running

In [41]:
from sklearn.svm import SVR

In [42]:
svr_model = SVR()
svr_model.fit(x_train,y_train)
y_pred = svr_model.predict(x_test)
mean_squared_error(y_test,y_pred)

5436757351.673235

**NOTE:** Wherever the least amount of error is present, that is the best on  
- LR - 2435389464.539427 **(least Error)**   
- KNN - 2975575455.8445354  
- DT - 5207771779.911838   
- SVR - 5436757351.673235   

### **Linear Regression(LR) is the Best Model as it has Least Error**

## **4. Model Deployment**

In [43]:
!pip install gradio

Requirement already satisfied: gradio in c:\users\ga\anaconda3\envs\eda-tools\lib\site-packages (6.11.0)
Requirement already satisfied: aiofiles<25.0,>=22.0 in c:\users\ga\anaconda3\envs\eda-tools\lib\site-packages (from gradio) (24.1.0)
Requirement already satisfied: anyio<5.0,>=3.0 in c:\users\ga\anaconda3\envs\eda-tools\lib\site-packages (from gradio) (4.10.0)
Requirement already satisfied: brotli>=1.1.0 in c:\users\ga\anaconda3\envs\eda-tools\lib\site-packages (from gradio) (1.2.0)
Requirement already satisfied: fastapi<1.0,>=0.115.2 in c:\users\ga\anaconda3\envs\eda-tools\lib\site-packages (from gradio) (0.135.3)
Requirement already satisfied: ffmpy in c:\users\ga\anaconda3\envs\eda-tools\lib\site-packages (from gradio) (1.0.0)
Requirement already satisfied: gradio-client==2.4.0 in c:\users\ga\anaconda3\envs\eda-tools\lib\site-packages (from gradio) (2.4.0)
Requirement already satisfied: groovy~=0.1 in c:\users\ga\anaconda3\envs\eda-tools\lib\site-packages (from gradio) (0.1.2)
Requirement already satisfied: hf-gradio<1.0,>=0.3.0 in c:\users\ga\anaconda3\envs\eda-tools\lib\site-packages (from gradio) (0.3.0)
Requirement already satisfied: httpx<1.0,>=0.24.1 in c:\users\ga\anaconda3\envs\eda-tools\lib\site-packages (from gradio) (0.28.1)
Requirement already satisfied: huggingface-hub<2.0,>=0.33.5 in c:\users\ga\anaconda3\envs\eda-tools\lib\site-packages (from gradio) (1.9.0)
Requirement already satisfied: jinja2<4.0 in c:\users\ga\anaconda3\envs\eda-tools\lib\site-packages (from gradio) (3.1.6)
Requirement already satisfied: markupsafe<4.0,>=2.0 in c:\users\ga\anaconda3\envs\eda-tools\lib\site-packages (from gradio) (3.0.2)
Requirement already satisfied: numpy<3.0,>=1.0 in c:\users\ga\anaconda3\envs\eda-tools\lib\site-packages (from gradio) (2.2.6)
Requirement already satisfied: orjson~=3.0 in c:\users\ga\anaconda3\envs\eda-tools\lib\site-packages (from gradio) (3.11.5)
Requirement already satisfied: packaging in c:\users\ga\anaconda3\envs\eda-tools\lib\site-packages (from gradio) (25.0)
Requirement already satisfied: pandas<4.0,>=1.0 in c:\users\ga\anaconda3\envs\eda-tools\lib\site-packages (from gradio) (2.3.3)
Requirement already satisfied: pillow<13.0,>=8.0 in c:\users\ga\anaconda3\envs\eda-tools\lib\site-packages (from gradio) (11.1.0)
Requirement already satisfied: pydantic<=3.0,>=2.0 in c:\users\ga\anaconda3\envs\eda-tools\lib\site-packages (from gradio) (2.12.5)
Requirement already satisfied: pydub in c:\users\ga\anaconda3\envs\eda-tools\lib\site-packages (from gradio) (0.25.1)
Requirement already satisfied: python-multipart>=0.0.18 in c:\users\ga\anaconda3\envs\eda-tools\lib\site-packages (from gradio) (0.0.24)
Requirement already satisfied: pytz>=2017.2 in c:\users\ga\anaconda3\envs\eda-tools\lib\site-packages (from gradio) (2025.2)
Requirement already satisfied: pyyaml<7.0,>=5.0 in c:\users\ga\anaconda3\envs\eda-tools\lib\site-packages (from gradio) (6.0.3)
Requirement already satisfied: safehttpx<0.2.0,>=0.1.7 in c:\users\ga\anaconda3\envs\eda-tools\lib\site-packages (from gradio) (0.1.7)
Requirement already satisfied: semantic-version~=2.0 in c:\users\ga\anaconda3\envs\eda-tools\lib\site-packages (from gradio) (2.10.0)
Requirement already satisfied: starlette<2.0,>=0.40.0 in c:\users\ga\anaconda3\envs\eda-tools\lib\site-packages (from gradio) (1.0.0)
Requirement already satisfied: tomlkit<0.14.0,>=0.12.0 in c:\users\ga\anaconda3\envs\eda-tools\lib\site-packages (from gradio) (0.13.3)
Requirement already satisfied: typer<1.0,>=0.12 in c:\users\ga\anaconda3\envs\eda-tools\lib\site-packages (from gradio) (0.24.1)
Requirement already satisfied: typing-extensions~=4.0 in c:\users\ga\anaconda3\envs\eda-tools\lib\site-packages (from gradio) (4.15.0)
Requirement already satisfied: uvicorn>=0.14.0 in c:\users\ga\anaconda3\envs\eda-tools\lib\site-packages (from gradio) (0.44.0)
Requirement already satisfied: fsspec in c:\users\ga\anaconda3\envs\eda-tools\lib\site-packages (from gradio-client==2.4.0->gradio) (2025.12.0)
Requirement already satisfied: exceptiongroup>=1.0.2 in c:\users\ga\anaconda3\envs\eda-tools\lib\site-packages (from anyio<5.0,>=3.0->gradio) (1.3.0)
Requirement already satisfied: idna>=2.8 in c:\users\ga\anaconda3\envs\eda-tools\lib\site-packages (from anyio<5.0,>=3.0->gradio) (3.11)
Requirement already satisfied: sniffio>=1.1 in c:\users\ga\anaconda3\envs\eda-tools\lib\site-packages (from anyio<5.0,>=3.0->gradio) (1.3.1)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\ga\anaconda3\envs\eda-tools\lib\site-packages (from fastapi<1.0,>=0.115.2->gradio) (0.4.2)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\users\ga\anaconda3\envs\eda-tools\lib\site-packages (from fastapi<1.0,>=0.115.2->gradio) (0.0.4)
Requirement already satisfied: certifi in c:\users\ga\anaconda3\envs\eda-tools\lib\site-packages (from httpx<1.0,>=0.24.1->gradio) (2026.1.4)
Requirement already satisfied: httpcore==1.* in c:\users\ga\anaconda3\envs\eda-tools\lib\site-packages (from httpx<1.0,>=0.24.1->gradio) (1.0.9)
Requirement already satisfied: h11>=0.16 in c:\users\ga\anaconda3\envs\eda-tools\lib\site-packages (from httpcore==1.*->httpx<1.0,>=0.24.1->gradio) (0.16.0)
Requirement already satisfied: filelock>=3.10.0 in c:\users\ga\anaconda3\envs\eda-tools\lib\site-packages (from huggingface-hub<2.0,>=0.33.5->gradio) (3.25.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in c:\users\ga\anaconda3\envs\eda-tools\lib\site-packages (from huggingface-hub<2.0,>=0.33.5->gradio) (1.4.3)
Requirement already satisfied: tqdm>=4.42.1 in c:\users\ga\anaconda3\envs\eda-tools\lib\site-packages (from huggingface-hub<2.0,>=0.33.5->gradio) (4.67.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\ga\anaconda3\envs\eda-tools\lib\site-packages (from pandas<4.0,>=1.0->gradio) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in c:\users\ga\anaconda3\envs\eda-tools\lib\site-packages (from pandas<4.0,>=1.0->gradio) (2025.2)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\ga\anaconda3\envs\eda-tools\lib\site-packages (from pydantic<=3.0,>=2.0->gradio) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in c:\users\ga\anaconda3\envs\eda-tools\lib\site-packages (from pydantic<=3.0,>=2.0->gradio) (2.41.5)
Requirement already satisfied: click>=8.2.1 in c:\users\ga\anaconda3\envs\eda-tools\lib\site-packages (from typer<1.0,>=0.12->gradio) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\ga\anaconda3\envs\eda-tools\lib\site-packages (from typer<1.0,>=0.12->gradio) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in c:\users\ga\anaconda3\envs\eda-tools\lib\site-packages (from typer<1.0,>=0.12->gradio) (14.3.3)
Requirement already satisfied: colorama in c:\users\ga\anaconda3\envs\eda-tools\lib\site-packages (from click>=8.2.1->typer<1.0,>=0.12->gradio) (0.4.6)
Requirement already satisfied: six>=1.5 in c:\users\ga\anaconda3\envs\eda-tools\lib\site-packages (from python-dateutil>=2.8.2->pandas<4.0,>=1.0->gradio) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\ga\anaconda3\envs\eda-tools\lib\site-packages (from rich>=12.3.0->typer<1.0,>=0.12->gradio) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\ga\anaconda3\envs\eda-tools\lib\site-packages (from rich>=12.3.0->typer<1.0,>=0.12->gradio) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\ga\anaconda3\envs\eda-tools\lib\site-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer<1.0,>=0.12->gradio) (0.1.2)

In [44]:
import gradio as gr

In [45]:
x.columns

Index(['SquareFeet', 'Bedrooms', 'Bathrooms', 'Neighborhood', 'YearBuilt'], dtype='object')

In [46]:
def prediction(SquareFeet , Bedrooms , Bathrooms , Neighborhood , YearBuilt):
    return lr_model.predict([[SquareFeet , Bedrooms , Bathrooms , Neighborhood , YearBuilt]])

In [47]:
prediction(2126,4,1,0,1969) # Gives approximate price prediction

C:\Users\GA\anaconda3\envs\eda-tools\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([235762.78562711])

In [48]:
df.head()

   SquareFeet  Bedrooms  Bathrooms  Neighborhood  YearBuilt          Price
0        2126         4          1             0       1969  215355.283618
1        2459         3          2             0       1980  195014.221626
2        1860         2          1             1       1970  306891.012076
3        2294         2          1             2       1996  206786.787153
4        2130         5          2             1       2001  272436.239065

In [49]:
interface = gr.Interface(fn = prediction, outputs = gr.Textbox("The House Price is:"), inputs = [gr.Number('Enter the Square_Feet in between 1000 to 3000'),
                      gr.Number('Enter the Number of Bedrooms between 1 to 5'),
                      gr.Number('Enter the Number of Bathrooms between 1 to 3'),
                      gr.Number('Enter the Neighborhood 0:Rural , 1:Suburb , 2:Urban'),
                      gr.Number('Enter the Year')])

In [50]:
interface.launch(share = True)

* Running on local URL:  http://127.0.0.1:7860
* Running on public URL: https://b9efd32de7cad84448.gradio.live

This share link expires in 1 week. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)